name: nanocurrency
description: A shared library implementing a Nano wallet
version: 0.1.0
homepage: https://github.com/getcanoe/nanocurrency
author: GÃ¶ran Krampe <goran.krampe@gmail.com>

environment:
  sdk: '>=2.1.0'

dependencies:
  test: ^1.5.2
  hex: ^0.1.2
  ed25519_dart:
    git:
      url: https://github.com/getcanoe/ed25519_dart
      ref: master
  pointycastle:
    git:
      url: https://github.com/getcanoe/pointycastle
      ref: master
